import Head from 'next/head'
import Header from '@components/Header'
import Footer from '@components/Footer'

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>mturro</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <Header title=A preface, an update: />

<p className="description">So, the following is kind of out of date - or at least not up to date. It, suffers from neglect, bitrot - it’s a victim of time. This page was written many years ago when both the web and I were young and it leaves out a significant chunk of my life. Specifically it ignores a professional transition I made quite a few years ago - a transition from working in digital workflows for print to working in, what had to that point been primarily a hobby, web development. Linux systems and server administration and web development had always been something I did for my weirdo friends and unfunded artists, but I eventually made that a full-on professional thing. Now I’m neck deep in Docker, containers, AWS, CI/CD, code reviews, git, and all sorts of tech shit. And I love it. So rather than try to re-write what comes below I figured I give it a preface. </p>
   <p className="description"> Also, speaking of git, this kind of brings a lot of me together in once place. I haven’t touched it in a while, but it’s there: <a href="https://github.com/mturro/poem">a github repo that is a poem too.</a> 

</p>
    <h2><strong>Who is <a rel="me" href="https://shakedown.social/@mturro">@mturro</a>?</strong></h2>
<p className="description">My name is Mike Turro and in my professional life I was (thus the strike through) <strike>the Director of Technology for <a href="http://www.mshanken.com" title="">M. Shanken Communications</a>, publisher of <a href="http://www.winespectator.com" title="">Wine Spectator</a>, <a href="http://www.cigaraficionado.com" title="">Cigar Aficionado</a>, <a href="http://marketwatchmag.com/" title="">Market Watch</a>, <a href="http://whiskyadvocate.com" title="">Whisky Advocate</a> and other fine magazines and applications</strike>. I have a new employer and if you find me interesting enough I’m sure you can summon the power of the internet to find my LinkedIn page. I’m also sure that you know (because you’re reading this and anyone with the ability to read should understand) that the words in this web place have nothing whatsoever to do with my professional life and are in no way endorsed by my employer. Well, they may be (endorsed), and they might be (indirectly about my professional life), just not as a matter of course. In fact I’m not even sure why I mention it–my professional life. I suppose it’s out of some kind of Copperfield/Caufield impulse to divulge what the cocktail party wants divulged. Forget I said anything about it.</p>

<p className="description">In my personal life I am a father, husband, son, son-in-law, brother, uncle, friend, and neighbor to a small group of individuals who take residence in the hills of North Jersey and other more remote areas of the country. A general and healthy fear of transforming the inherently private into the overtly public keeps me from diving too deep into the pool with regard to all that though. It’s a shame really. My kids are cute… adorable even. Still, it should be enough if you just know that I have a super happy personal life and feel totally content with all that–almost to the point of complacency. Really, it’s a wonder I even dare disturb that universe by playing with words here and now… in this web place. </p>

<h2><strong>Working from real life back to books…</strong></h2>
<p className="description">A random fact about me that for some reason I feel compelled to talk about here: I walked away from my Master of Arts Degree in Literature with only six credits left to complete.  After reading Marshall McLuhan I decided that I needed to get out of the academic trap. I needed to understand the practical effects and biases of the media I offhandedly consumed. As I saw it the only way to effectively do that was to get my hands dirty–to understand the media I used so that it couldn’t use me. The time had come to shift from consumer to maker. </p>

<p className="description">So I started banging around on a friend’s <a href="http://en.wikipedia.org/wiki/Power_Macintosh_7200">PowerMac 7200</a> (the first time I ever saw a color monitor and a web browser) and produced some crude, colorful, web pages. I was also quite lucky(?) that the 7200 had  <a href="http://en.wikipedia.org/wiki/QuarkXPress">Quark Xpress 3</a> installed - that kind of software didn’t often find it’s way into the hands of pizza delivering grad students. Being the sort of college-aged idealist I was I channeled this new found technical capacity into founding an arts collective with some friends. The new Bluepear Arts Collective was going to change the world. It was going to use the Internet to give voice to the voiceless and power to the powerless. Who needed record contracts when we had dial-up?</p>

<p className="description">It was then, in between poems, that I started writing code. In pretty short order I realized I had a knack for operational thinking. I could break the technology down and figure out how to get ideas from “what-if” to “there it is” fairly quickly. Before long that operational fluency with the web was being extended, pro-bono, to all our artist friends and beyond. Whether it was hosting downloads of shows for friends in Germany, demos for the band next door, art for the barista at the cafe downtown, or subversive ideas for the philosophy major working the counter at the bookstore, Bluepear was not only willing, but able to help. </p> 

<p className="description">Eventually I got  good enough at the technical aspects of digital production that I scored a job with a magazine publisher (or as they now like to refer to themselves - <a href="http://www.penton.com" title="">a media company</a>). I was extraordinarily lucky to get into the business at a time when the computer - the Mac really - was transforming the printing and publishing world.  I grew up on Apple so the Mac was natural to me - I was well versed in its culture and its application as a creative tool.  This understanding gave me a leg up on people who had been in the business for decades, people who had (jokingly?) claimed to set type in <a href="http://en.wikipedia.org/wiki/Hot_metal_typesetting" title="">hot metal</a>, people who looked at the Mac with scorn. It was only natural that I would become the tech guy, the guy who knew about email and servers and this thing called the Internet. The only guy who took the time to <a href="http://en.wikipedia.org/wiki/RTFM">RTFM</a>.</p>

<p className="description"> So I dove into learning how magazines actually get made.  I learned about web offset printing, computer to plate technologies, fonts (sigh, fonts), trapping, line screen, halftones, copy-dot, drum, chromes, color keys. I learned about the real life bargain between art and commerce that comprises the fundamental core of media. I learned about the ecosystem of technologies and individuals that fuel media. With a healthy respect for the tools of media past, present, and future I was able to bring new technical efficiencies to an age old process. Bridging the worlds of the web and the web-offset I was able to use code to build automated workflows. It was the kind of efficiency that managers love. I was golden boy. </p>

<p className="description">Eventually though Web 1.0 flamed out and obliterated the advertising budgets of all the tech companies that were advertising in those magazines. I found that I had a little free time on my hands so I put my experience to some good use. A friend had been writing and distributing <a href="http://www.amazon.com/The-Bus-a-Novel/dp/0970197217/ref=sr_1_1?s=books&amp;ie=UTF8&amp;qid=1339099709&amp;sr=1-1">a book on Phish tour about Phish tour</a>. The people of Shakedown loved it. I loved it. I love it still. So I formed a company and helped my good friend drop his novel on the world in proper fashion. We hit the first <a href="http://www.youtube.com/watch?v=fELJJaqc_ko/">Bonnaroo</a> and <a href="https://www.youtube.com/watch?v=FIyRLRj4wlo">the Gathering of the Vibes,</a> and sold a few copies. I didn’t make any money. In fact I lost some. Yet, when I think about those days I feel richer.  What sticks with me from that time is the conversation, the hope, the community. Those things are part of me now. Everything in my professional life that followed has been and will continue to be based on what I learned in so many parking lots along so many roads.</p>

<p className="description">All in all I am happy I walked away from academics and found real life waiting for me in the media and publishing worlds.  I’m not sure I could see myself being happy teaching <a href="http://en.wikipedia.org/wiki/Herman_Melville" title="">Mellville</a> and <a href="http://en.wikipedia.org/wiki/Ralph_Waldo_Emerson" title="">Emerson</a> and <a href="http://en.wikipedia.org/wiki/Henry_David_Thoreau" title="">Thoreau</a> to college kids.  Not that there is anything wrong with that… I come from a family of teachers - I’m even married to one… it’s just that it never felt like a fit for me.  I need to be confronted with market level uncertainty… I love to (here I will paraphrase <a href="http://en.wikipedia.org/wiki/Nassim_Taleb" title="">Nassim Nicholas Taleb</a>) work from real life back to books, not from books to real life.</p>

<p className="description">If after all of the above you feel like I might be of some help to you, or you might be of some help to me, or you just want to say hello, feel free to attempt <a href="http://twitter.com/mturro">contact</a>.</p>
      </main>

      <Footer />
    </div>
  )
}
